# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
filepath = 'output_data/citydata.csv'
df_cityweather = pd.read_csv(filepath)
df_cityweather.head()

,city,lat,long,max_temp,humidity,cloudiness,wind_speed,country,date
0,khatanga,71.9667,102.5000,86.61,42,59,10.92,RU,1627383071
1,saldanha,-33.0117,17.9442,60.85,75,22,17.92,ZA,1627383130
2,haftoni,38.7632,48.7622,93.99,45,40,13.80,AZ,1627383130
3,tuktoyaktuk,69.4541,-133.0374,45.01,76,100,8.52,CA,1627383130
4,ushuaia,-54.8000,-68.3000,35.26,87,75,4.61,AR,1627383130

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [24]:
locations = df_cityweather[["lat", "long"]]
humidity = df_cityweather['humidity'].astype(float)

In [35]:
# Plot Heatmap
fig = gmaps.figure(center = (0,0),zoom_level=2)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=30,
                                 point_radius=3)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [42]:
df_vacation_candidates = df_cityweather.loc[(df_cityweather['max_temp']<85) & (df_cityweather['max_temp']>75)
                                           & (df_cityweather['cloudiness']<30)
                                           & (df_cityweather['wind_speed']<8)
                                           & (df_cityweather['humidity']< 50)
                                         ]

df_vacation_candidates.dropna()
df_vacation_candidates

,city,lat,long,max_temp,humidity,cloudiness,wind_speed,country,date
128,east wenatchee bench,47.4257,-120.2812,79.92,46,1,1.01,US,1627383152
129,yerbogachen,61.2767,108.0108,84.96,43,1,5.06,RU,1627383152
157,nikolskoye,59.7035,30.7861,84.09,29,3,5.03,RU,1627383157
166,sao raimundo das mangabeiras,-7.0219,-45.4811,77.27,45,4,6.26,BR,1627383158
235,storforshei,66.4043,14.5233,82.18,48,20,3.44,NO,1627383170
345,araguaina,-7.1911,-48.2072,76.24,39,4,4.90,BR,1627383189
405,caceres,39.5220,-6.3748,84.79,25,0,7.18,ES,1627383200
436,kemijarvi,66.7131,27.4306,76.57,41,5,2.08,FI,1627383206
481,santa rosalia,27.3167,-112.2833,83.19,48,0,3.76,MX,1627382714
519,lerida,41.6167,0.6167,84.88,48,0,4.61,ES,1627383221

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure